on:
  push:
    branches:
    - test-ci

jobs:
  Build:
    name: Build Package
    strategy: 
      fail-fast: false
      matrix:
        settings:
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          
    runs-on: ${{ matrix.settings.host }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.0
    - name: Setup Node
      uses: actions/setup-node@v3.8.1
      with:
       node-version: 18
    - name: Setup Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: '3.9'
    - name: Install
      run: npm install && npm run build
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: bindings-${{ matrix.settings.target }}
        path: |
          ./build/Release/*.node
        if-no-files-found: error
        
    
