on:
  push:
    branches:
    - test-ci

jobs:
  Build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.0
    - name: Setup Node
      uses: actions/setup-node@v3.8.1
      with:
       node-version: 18
    - name: Setup Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: '3.9'
    - name: Install
      run: npm install
      
        
    
